thpbrite_like/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'

  get '/admin', to: 'static_pages#admin', as: 'admin'
  delete '/admin', to: 'users#destroy'
  get '/about', to: 'static_pages#about', as: 'about'
  get  '/signup',  to: 'users#new', as: 'signup'

  resources :users

  get    '/login',   to: 'sessions#new', as: 'login'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy', as:'logout'

  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

thpbrite_like/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

thpbrite_like/app/models/event.rb
class Event < ApplicationRecord
  
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendees

end

thpbrite_like/app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
  validates :date, presence: true
  validates :place, presence: true
end

thpbrite_like/app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 },
                   uniqueness: true

  has_secure_password

  validates :password, presence: true, length: { minimum: 6 }

  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  has_many :event_attendees, foreign_key: 'attendee_id'
  has_many :attending_events, through: :event_attendees, source: :event

end

thpbrite_like/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include EventsHelper
end

thpbrite_like/app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @current_user = current_user
    @event = Event.new(params_event)
    @event.creator_id = @current_user.id
    @event.save
    if @event.errors.full_messages.empty?

      flash[:succes] = 'Event enregistré !'
      redirect_to events_path
    else
      flash[:error] = 'Error'
      redirect_to events_path
    end
  end

  def show
    @event = Event.find(params[:id])
  end


  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path
  end

  def update

  end

  def index
    @events = Event.all
    lol_date(@events)
  end


  private

  def params_event
    params_event = params.require(:event).permit(:description, :place, :date, :id)
  end
end

thpbrite_like/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:succes] = "Welcome ! Access permitted !"
      redirect_to root_url
    else
      flash[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

thpbrite_like/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @current_user = current_user
  end
  def admin
    @users = User.all
  end
  def about
  end
end

thpbrite_like/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params_user)
    if @user.errors.full_messages.empty?
      flash[:succes] = 'Profil enregistré, veuillez vous connecter svp.'
      redirect_to login_url
    else
      flash[:error] = 'Rentre bien un pseudo et un mot de passe convenable !'
      redirect_to signup_url
    end
  end

  def show
    @user = User.find(params[:id])
    # @comment = Comment.new
    # @comments = Comment.where(gossip_id: params[:id])
  end

  def edit
    # @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_path
  end

  def update
    # @user = User.find(params[:id])
    # @user.update(params_user)
    # if @user.save
    #   redirect_to gossip_path(@user.id)
    # else
    #   flash[:error] = 'Rentre bien un pseudo et un texte !'
    #   redirect_to edit_gossip_path
    # end
  end

  def index

  end

  private

  def params_user
    params_user = params.require(:user).permit(:name, :password)
  end
end

thpbrite_like/app/helpers/application_helper.rb
module ApplicationHelper
end

thpbrite_like/app/helpers/events_helper.rb
module EventsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


    def lol_date(events)
      now = Time.now
      @past_events = []
      @future_events = []
      events.each do |event|
        if event.date > Time.now
          @future_events << event
        else
          @past_events << event
        end
      end
      @future_events
      @past_events
    end

end

thpbrite_like/app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
  !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

thpbrite_like/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

thpbrite_like/app/helpers/users_helper.rb
module UsersHelper
end

thpbrite_like/app/views/events/edit.html.erb
<div class="content">
<% provide(:title, "Update event") %>
<h1><%= current_user.name.capitalize %>, you could update an event here.</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @event, url: {action: "update"} do |f| %>


      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, size: "50x3", class: 'form-control' %>

      <br>
      <%= f.label :place %>
      <%= f.text_field :place, size: "20x3", class: 'form-control' %>
      <br>

        <%= f.submit "Send it !", class: "btn btn-primary" %>
      <% end %>
      <br>
  </div>
</div>
</div>

thpbrite_like/app/views/events/index.html.erb
<div class="content">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">Liens</th>
        <th scope="col">Date</th>
        <th scope="col">Description</th>
        <th scope="col">Place</th>
        <th scope="col">Creator</th>
        <th scope="col">Attendees</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td><strong>Events will coming ...</strong></td>
        <td> </td>
        <td> </td>
        <td> </td>
        <td> </td>
        <td> </td>
        <td> </td>
      </tr>
      <% @future_events.each do |event| %>
        <tr>
          <th scope="row"><a href="<%= event_path(event.id) %>">Go</a></th>
          <td><%= event.date %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.creator.name %></td>
          <td><%= link_to 'Add buddies ...', class: 'btn btn-outline-secondary'%></td></td>
          <td><%= link_to 'Delete', event, class: 'btn btn-outline-danger',
                                    method: :delete,
               data: { confirm: 'Sur ?' } %></td>
        </tr>
        <% end %>
        <tr>
        <td><strong>Events already passed ...</strong></td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
          <td> </td>
        </tr>
        <% @past_events.each do |event| %>
        <tr>
          <th scope="row"><a href="<%= event_path(event.id) %>">Go</a></th>
          <td><%= event.date %></td>
          <td><%= event.description %></td>
          <td><%= event.date %></td>
          <td><%= event.creator.name %></td>
          <td><%= link_to 'Add buddies ...', class: 'btn btn-outline-secondary'%></td></td>
          <td><%= link_to 'Delete', event, class: 'btn btn-outline-danger',
                                    method: :delete,
               data: { confirm: 'Sur ?' } %></td>
        </tr>

        <% end %>
    </tbody>
  </table>

</div>

thpbrite_like/app/views/events/new.html.erb
<div class="content">


<% provide(:title, "New event") %>
<h1><%= current_user.name.capitalize %>, you could create an event here.</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:event, url: {action: "create"}) do |f| %>

      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>
      <br>
      <%= f.label :description %>
      <%= f.text_area :description, size: "50x3", class: 'form-control' %>

      <br>
      <%= f.label :place %>
      <%= f.text_field :place, size: "20x3", class: 'form-control' %>
      <br>

        <%= f.submit "Send it !", class: "btn btn-primary" %>
      <% end %>
      <br>
  </div>
</div>
</div>

thpbrite_like/app/views/events/show.html.erb
<div class="content">
    <h3>
      <strong><%= @event.creator.name %></strong> a créé l'event suivant :
    </h3>
    <h4>Date :</h4>
    <p class="eventS">
      <%= @event.date %>
    </p>
    <h4>Lieu :</h4>
    <p class="eventS">
      <%= @event.place %>
    </p>
    <h4>Description :</h4>
    <p class="eventB">
      <%= @event.description %>
    </p>
    <h4>Attendees :</h4>
    <p class="eventB">
      <%= @event%>
    </p>


</div>

thpbrite_like/app/views/layouts/_header.html.erb
<div class="maxime">


<nav class="navbar navbar-inverse navbar-fixed-left">
    <div class="container">
      <div class="navbar-header">

        <% if !logged_in? %>
        <a class="navbar-brand" href="<%= root_path %>">THP-brite Like</a>
        <% else %>
        <a class="navbar-brand" href="<%= root_path %>">Hello <%= current_user.name %><br>Page d'accueil</a>
        <% end %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <% if !logged_in? %>
            <li><%= link_to "Sign up", new_user_path, class: "btn btn-info" %></li>
            <br>
            <li><a href="<%= login_path %>" class="btn btn-info">Log in</a></li>
          <% else %>
            <li> <a href="<%= new_event_path %>" class="btn btn-secondary" >Créer un event</a></li>
            <li> <a href="<%=events_path%>" class="btn btn-secondary" >Voir les events</a></li>
            <!-- <li> <a href="<%=events_path%>" class="btn btn-secondary" >Voir les events</a></li>
            <li> <a href="<%=events_path%>" class="btn btn-secondary" >Voir les events</a></li> -->
            <li><a href="<%= admin_path %>" class="btn btn-secondary" >Gestion des utilisateurs</a></li>
            <li><%= link_to "Log out", logout_path, method: :delete, class: "btn btn-danger" %></li>
          <% end %>
          <!-- <li><a href="<%= admin_path %>">Admin pas caché</a></li> -->

        </ul>
      </div>
    </div>
  </nav>
</div>

thpbrite_like/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPbrite-Like TeamBDX massimo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/paper/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

thpbrite_like/app/views/static_pages/about.html.erb
<div class="content">


    <h1>About Team BDX</h1>
    <p>Bab & Max</p>


</div>

thpbrite_like/app/views/static_pages/admin.html.erb
<div class="content">

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Pseudo</th>
        <th scope="col">Valid</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each_with_index do |user, i| %>
        <tr>
          <th scope="row"><%= i+1 %></th>
          <td><%= user.name %></td>
          <td><%= user.present? %></td>
          <td><%= link_to 'Delete', user, class: 'btn btn-outline-danger',
                                    method: :delete,
               data: { confirm: 'Sur ?' } %></td>
        </tr>
        <% end %>
    </tbody>
  </table>

</div>

thpbrite_like/app/views/static_pages/index.html.erb
<div class="content">
  <div class="box">
    <% if logged_in? %>
      <h1>Hello <%= @current_user.name %>!</h1>
      <br>
      <h3>Welcome to this Eventbrite-like site, made by <strong>@massimo</strong>.
      <br> Thx so much to <strong>@bab</strong> for helping !
      <br> <strong>#TeamBDX</strong> </h3>
    <% else %>
      <br><br><br><br><br><br>
      <h4 class="btn btn-danger">Connexion requise pour aller sur ce site.</h4>
    <% end %>
  </div>
  <div class="bdx">
    <img src="https://image.noelshack.com/fichiers/2018/18/4/1525373439-thp-bdx.png" alt="logo thp bdx" class="logo"/>
    </div>
</div>

thpbrite_like/app/views/users/new.html.erb
<div class="content">
  <div class="box">
        <% provide(:title, 'Sign up') %>
        <h1>Sign up</h1>

        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for(@user, url: {action: "create"}) do |f| %>

            <h4 class="text-danger" id="error"><%= flash[:succes] %></h4>
            <h4 class="text-danger" id="error"><%= flash[:error] %></h4>

              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
<br>
              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
<br>
              <%= f.label :password_confirmation, "Confirmation" %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
<br>
              <%= f.submit "Create my account", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
</div>
</div>

thpbrite_like/app/views/users/show.html.erb
<div class="content">
  <div class="inside">
    <h1>Hello <%= @user.name %></h1>
  </div>
  <div class="inside">
    <h3>Voici ta page.</h3>
    <h5>Que souhaites-tu faire ici :</h5>

    <ul>
      <li><a href="#">Créer un nouvel évènement !</a></li>
    </ul>
  </div>
</div>